### ISSUE TITLE
entity not accessible on imported event classes

### ISSUE THREAD

**Issue by phemmer** [btk5h/skript-mirror#117]
**Describe the bug**
The `entity`/`player`/etc are not accessible on imported event classes 

**To reproduce**
```
import:
  org.bukkit.event.player.PlayerDropItemEvent
on PlayerDropItemEvent:
  broadcast "entity: %entity%"
  broadcast "player: %player%"
```
```
skript reload test
```

**Expected behavior**
Success

**Screenshots**
```
[Skript] Reloading test.sk...
loading 'test.sk'
import (import):
PlayerDropItemEvent ([class org.bukkit.event.player.PlayerDropItemEvent] priority HIGH):
There's no entity in an on bukkit event event (from ch.njol.skript.expressions.base.EventValueExpression.init(EventValueExpression.java:149)) (test.sk, line 4: broadcast "entity: %entity%"')
There's no player in an on bukkit event event (from ch.njol.skript.expressions.base.EventValueExpression.init(EventValueExpression.java:149)) (test.sk, line 5: broadcast "player: %player%"')
loaded 2 triggers and 0 commands from 'test.sk'
Commands unchanged, not syncing them to clients
[Skript] Encountered 2 errors while reloading test.sk!
```

**Server information**
- skript-mirror: 1.0.0
- Skript: 2.3.2
- Bukkit: PaperMC 1.13 build 495
- Minecraft: 1.13
- Java: openjdk version "1.8.0_191"
- OS: Linux - Fedora 28

**Additional context**
If `PlayerDropItemEvent` is changed to just `Drop`, everything works fine. Thus it is my assumption that something is missing when skript-mirror is generating the trigger for the imported class.

**Comment by btk5h** [comment]
Working as intended. You must use methods of the `event` expression to get event-values.

**Comment by phemmer** [comment]
Is there any documentation on this? This seems like surprising behavior to me. Given that the expressions `player` and `entity` are the standard way to refer to them within skript, it seems highly desirable to be able to refer to them as such.

**Comment by btk5h** [comment]
skript-mirror does not know anything about the event, so you must explicitly specify the method you want to call. I will clarify this in the documentation.

**Comment by Snow-Pyon** [comment]
@phemmer those are event values, which are registered when the addon is loaded, skript-mirror can't register those since it doesn't know what event are you gonna use until the addon is loaded.

Just use the methods provided by the event.

**Comment by btk5h** [comment]
> @phemmer those are event values, which are registered when the addon is loaded, skript-mirror can't register those since it doesn't know what event are you gonna use until the addon is loaded.

Actually, since it's only a class lookup, the class (and it's methods) can be determined before the addon is loaded. The issue is due to two factors:
* Skript does not allow registering event values conditionally. Custom events all use the same event class under the hood, so the event-value would be registered for all events. This forces errors to be thrown at run-time rather than parse-time.
* It is not always clear which method should map to which event-value (see the case of the damage event). This would lead to inconsistent event-value behavior across different events.

**Comment by phemmer** [comment]
> Custom events all use the same event class under the hood

I think this pretty well explains the current behavior then.

Would it be difficult to add additional skript-mirror classes for the major event classes bukkit provides (`org.bukkit.event.block`, `.enchantment`, `.entity`, etc), and then provide the event-values (expressions) such as `player` only when the imported class subclasses a bukkit class providing the appropriate getter, such as `.getPlayer()`?
This should solve the vast majority of the use cases. And it delegates the 'multiple event-value of same type' problem to the class, and whatever its getter returns.

**Comment by btk5h** [comment]
If possible, I would like to avoid any instances of "why does this work here, but not here". It's preferable to have a simple explanation like "custom events don't use event-values" rather than "depending on the type of your event, here are the event-values that are supported".

**Comment by phemmer** [comment]
But skript already does exactly that. For example if you try to use `projectile` on a `Jump`, you get:
```
There's no projectile in an on jump event (from ch.njol.skript.expressions.base.EventValueExpression.init(EventValueExpression.java:149)) (test.sk, line 2: broadcast "%projectile%"')
```

&nbsp;

I'm also having trouble getting this to work even using the event methods.
Below is an example where I want to remove an ender pearl from inventory on use of a warp. *(I'm using `org.bukkit.event.player.PlayerTeleportEvent` here just as an example that can be reproduced easily)*

```
import:
        org.bukkit.event.player.PlayerTeleportEvent
on PlayerTeleportEvent:
        event.getPlayer() doesn't have  1 ender pearl:
                send "Need an ender pearl to warp" to event.getPlayer()
                cancel the event
        remove 1 ender pearl from event.getPlayer()
```

```
[Skript] Reloading test.sk...
loading 'test.sk'
import (import):
PlayerTeleportEvent ([class org.bukkit.event.player.PlayerTeleportEvent] priority HIGH):
    null doesn't contain [[itemtype:ender pearl]]:
        send "Need an ender pearl to warp" to null
        cancel event
null can't have anything removed from it (from ch.njol.skript.effects.EffChange.init(EffChange.java:186)) (test.sk, line 7: remove 1 ender pearl from event.getPlayer()')
loaded 2 triggers and 0 commands from 'test.sk'
Commands unchanged, not syncing them to clients
[Skript] Encountered 1 error while reloading test.sk!
```

**Comment by btk5h** [comment]
It's immediately obvious that a jump event doesn't have a projectile. There may be other plugin events that seem like they should have a certain event-value, but don't.

As for your other issue, does that issue with the final line still occur even when you set a variable to `event.getPlayer()`?

**Comment by phemmer** [comment]
> As for your other issue, does that issue with the final line still occur even when you set a variable to `event.getPlayer()`?

The issue does indeed go away, thanks. However that seems like another surprise that requires the developer to be aware of.

So the way I'm seeing it there are 2 avenues:
1) Keep as is, with 2 unexpected behaviors documented: 1) Can't use `player`/`entity`/etc. 2) event methods must be stored in a variable.
2) Add bukkit's major event classes and document the event-values they support.

Neither is ideal no, but I personally view # 2 as the lesser of the 2 evils.

I don't have anything else to add, so I'll leave it to you from here.

Thanks for the plugin, and the assistance with the issue :-)

**Comment by Snow-Pyon** [comment]
It can't register the event values anyways because registering event values to their superinterfaces (EntityEvent for example) is somewhat buggy in Skript, in fact, Skript already registers the event values for the superinterfaces (EntityEvent, BlockEvent, PlayerEvent, etc) but since it is buggy, it doesn't work here.

**Comment by phemmer** [comment]
Actually, it seems like there's yet another surprise somewhere to be documented.

```
on Jump:
  set {_player} to event.getPlayer()
  if {_player} doesn't have 1 ender pearl:
    send "No ender pearl" to {_player}
    stop
  send "You have ender pearl" to {_player}
```
This script results in always sending "No ender pearl", even if the player has one in inventory.

However this works fine:
```
on Jump:
  if player doesn't have 1 ender pearl:
    send "No ender pearl" 
    stop
  send "You have ender pearl" 
```

Granted I suspect this is not something specific to skript-mirror, but skript itself. However since skript-mirror is forcing the use of `event.getPlayer()`, I think this should be documented by skript-mirror (whatever "this" is, and however you're supposed to fix it).

**Comment by btk5h** [comment]
If that's an issue with all players stored in variables, that's a Skript issue, not a skript-mirror one.

**Comment by phemmer** [comment]
Yes, but see the last paragraph. 

> Granted I suspect this is not something specific to skript-mirror, but skript itself. However since skript-mirror is forcing the use of `event.getPlayer()`, I think this should be documented by skript-mirror (whatever "this" is, and however you're supposed to fix it).

&nbsp;

skript-mirror is preventing the usage of the officially supported mechanism for accessing these values. Therefore I think it's skript-mirror's responsibility to provide a functional and documented alternate access mechanism.

**Comment by Snow-Pyon** [comment]
> skript-mirror is preventing the usage of the officially supported mechanism for accessing these values. Therefore I think it's skript-mirror's responsibility to provide a functional and documented alternate access mechanism

**Comment by Snow-Pyon** [comment]
> skript-mirror is preventing the usage of the officially supported mechanism for accessing these values. Therefore I think it's skript-mirror's responsibility to provide a functional and documented alternate access mechanism

skript-mirror isn't preventing it, it *can't* provide support for it due to the issues explained above, the alternate way (which is actually the "official" way but anyways) is using the getters of the event. The fact that the above piece of code doesn't work properly is indeed a Skript bug that you just happened to reproduce with skript-mirror, but that doesn't mean it's the cause of it.

**Comment by phemmer** [comment]
> skript-mirror isn't preventing it, it can't provide support for it due to the issues explained above

Explaining why skript-mirror is preventing it doesn't change the fact that skript-mirror is preventing it...

&nbsp;

> the alternate way (which is actually the "official" way but anyways) is using the getters of the event

I don't understand this statement. The usage of `player` is directly documented:
![image](https://user-images.githubusercontent.com/1826947/52103547-2ebd2700-25b4-11e9-9c60-99b56ef19581.png)
![image](https://user-images.githubusercontent.com/1826947/52102952-4fd04880-25b1-11e9-9116-83dcdf2b98fe.png)
...and is used in tons of examples.

&nbsp;

> The fact that the above piece of code doesn't work properly is indeed a Skript bug that you just happened to reproduce with skript-mirror, but that doesn't mean it's the cause of it.

All signs indicate it is. Look at the debug output of the normal, and then the skript-mirror versions of the same script, when they are loaded.
Normal:
```
on Jump:
  if player doesn't have 1 ender pearl:
    send "No ender pearl"
    stop
  send "You have ender pearl"
```
```
Jump (simple event):
    (the player >> ch.njol.skript.classes.data.DefaultConverters$1@5906d0b3: org.bukkit.entity.Player->org.bukkit.inventory.Inventory) doesn't contain [[itemtype:ender pearl]]:
        send "No ender pearl" to event-player/console
        stop 2 sections
    send "You have ender pearl" to event-player/console
```
skript-mirror:
```
on Jump:
  set {_player} to event.getPlayer()
  if inventory of {_player} doesn't have 1 ender pearl:
    send "No ender pearl" to {_player}
    stop
  send "You have ender pearl" to {_player}
```
```
Jump (simple event):
    set {_player}(as java.lang.Object) to null
    inventory of {_player}(as org.bukkit.inventory.InventoryHolder) doesn't contain [[itemtype:ender pearl]]:
        send "No ender pearl" to {_player}(as org.bukkit.command.CommandSender)
        stop 2 sections
    send "You have ender pearl" to {_player}(as org.bukkit.command.CommandSender)
```
Note how in the normal script, `player` is properly converted to the appropriate object. Where as in skript-mirror it comes out as `java.lang.Object`.

&nbsp;

In any case, I finally got back to this, and managed to come up with a workaround:
```
on Jump:
  set {_player} to event.getPlayer()
  if inventory of {_player} doesn't have 1 ender pearl:
    send "No ender pearl" to {_player}
    stop
  send "You have ender pearl" to {_player}
```

&nbsp;

All these issues just exemplify the problem with having to use getters instead of having support for the native expressions.

**Comment by btk5h** [comment]
> Note how in the normal script, player is properly translated with a converter. Where as in skript-mirror it comes out as java.lang.Object.

This is the standard behavior of variables.

Other than improving the documentation and debug output, I don't think much more needs to be done in this area. Native Skript events can provide event-values since they can be written in such a way that the appropriate event-values can be accessed the same way regardless of how the underlying event is designed. The best skript-mirror can do is take a guess, but that would be incredibly messy to implement and can still lead to confusion about which events support which event-values.

**Comment by Snow-Pyon** [comment]
> I don't understand this statement. The usage of player is directly documented:
...and is used in tons of examples.

Skript documentation != skript-mirror documentation
as btk5h just explained above, Skript is able to provide event values, that doesn't mean **every** event must provide them.

There are also events that don't support event values from other addons. I understand that you find it common but you have to understand that a reflective event *isn't* just another event like `on click`, it's a "special" event which lets you listen anything that extends Event, even the ones that don't have such event values. You might say that the events that have those events values should provide them, but that's just messy and will end up like people asking why their script doesn't work for x event and not for others (a simple example of this is the periodical event, people seem to think there is a player involved in that event when it isn't the case, doesn't mean we should make it a thing).
